// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_download_video from "./routes/api/download-video.ts";
import * as $api_generate_video from "./routes/api/generate-video.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_list_videos from "./routes/api/list-videos.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $VideoGenerator from "./islands/VideoGenerator.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/download-video.ts": $api_download_video,
    "./routes/api/generate-video.ts": $api_generate_video,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/list-videos.ts": $api_list_videos,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/VideoGenerator.tsx": $VideoGenerator,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
